name: make and publish docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Make docs
      uses: mattnotmitt/doxygen-action@v1
      with:   
         working-directory: .
         doxyfile-path: ./Doxyfile
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add --force docs
        git commit -m "Docs for $GITHUB_SHA" -a
        git subtree push --prefix=docs origin gh-pages
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        publish-directory: docs
